### ISSUE TITLE
Questions on compute_mutation_keys and variabes

### ISSUE THREAD

**Issue by robwolff3** [sullivtr/terraform-provider-graphql#36]
Hey guys I'm back with another question about a setup I have here.

This resource I'm creating in our graphql api is tracked by a ID called srn and the value for srn is generated at the time of resource creation. When I run the create mutation I get the following output.

```graphql
{
  "data": {
    "CreateSonraiInvites": {
      "items": [
        {
          "srn": "srn::SonraiInvite/a282887d-89e1-4fa5-92a9-05626a475821",
          "email": "rob.wolff@domain.com",
          "dateSent": "2021-05-28T21:41:35.239+00:00",
          "expiry": "2021-06-02T21:41:35.239+00:00",
          "isPending": true,
          "pendingRoleAssignments": {...}
        }
      ]
    }
  }
}
```

And here is my `main.tf`

```terraform
resource "graphql_mutation" "user_invite" {
  mutation_variables = {
    "name" = var.name
    "email" = var.email
    "scope" = var.scope
  }

  read_query_variables = {
    "srn" = "SonraiInvites.items.srn"
  }

  compute_from_create = true

  compute_mutation_keys = {f
    "srn" = "CreateSonraiInvites.items.srn"
  }

  create_mutation = file("./queries/user_invite_create.graphql")
  update_mutation = file("./queries/user_invite_update.graphql")
  delete_mutation = file("./queries/user_invite_delete.graphql")
  read_query      = file("./queries/user_invite_read.graphql")
}
```

In order to read or delete this resource I need to reference it by the srn generated at creation. Your documentation is really good but I keep getting tripped up on how to get that srn ID from the create mutation output and input it as the variable `$srn` in the read query and delete mutation. I think I have `compute_from_create = true` correct as the srn ID has to come from the create mutation.

P.S. a side question. I get the same output from the create mutation as a I do from the read query. Also, in our api the resource I am creating it does not have an update operation, just create, read and delete. Leaving the update graphql file blank seems to keep things moving forward. Doesn't that negate the need form a read query or update mutation in this case?

Any help would be appreciated. Thank you!

**Comment by sullivtr** [comment]
@robwolff3 This is a great question. I have a PR to make this possible open here -> https://github.com/sullivtr/terraform-provider-graphql/pull/29

As of right now (version 1.4.6) the provider is not able to find a key within a list of items. 

I originally chose not to make this possible because it can be very dangerous to reference state that can change easily such as items in an array. Even after I merge the above linked PR, I'd advise you to avoid doing so if you can. For example, if the item in the list is at index 0, and next week you run your TF template, and the query returns 2 items, and the one you reference is now at index 1, your state will be broken and you will be referencing information for the incorrect object. 

With that said, my goal is to get the above referenced feature released in the near future.

**Comment by sullivtr** [comment]
To be more clear with examples, if the response looked like this: 
```
{
  "data": {
    "Invite": {
          "srn": "srn::SonraiInvite/a282887d-89e1-4fa5-92a9-05626a475821",
          "email": "rob.wolff@domain.com",
          "dateSent": "2021-05-28T21:41:35.239+00:00",
          "expiry": "2021-06-02T21:41:35.239+00:00",
          "isPending": true,
          "pendingRoleAssignments": {...}
        }
  }
}```
you could easily grab the srn property with `Invite.srn` 

However, since the object is in a list, it will not be able to find it

**Comment by sullivtr** [comment]
@robwolff3  I am actually going to close this issue now since there is already an open issue related to this feature [HERE](https://github.com/sullivtr/terraform-provider-graphql/issues/23)

**Comment by sullivtr** [comment]
@robwolff3 I changed my mind, and got the PR merged just now. A new version will be released soon with v1.5.0. You can upgrade to that version and be able to compute the SRN value as follows: 

```hcl
  compute_mutation_keys = {f
    "srn" = "CreateSonraiInvites.items[0].srn"
  }
```

**Comment by robwolff3** [comment]
That is awesome. Thank you so much!

**Comment by robwolff-sonrai** [comment]
@sullivtr Tried out the PR and the create and delete are working great. In my example am I able to pass the srn ID from the create mutation in as the variable `$srn` under the read_query_variables?

**Comment by sullivtr** [comment]
@robwolff-sonrai Great question. Yes you can. 

Any key:values computed from the `compute_mutation_keys` map can be used inside of your graphql queries. So take this example:

You are computing the value of `srn` like this: 
```hcl
 compute_mutation_keys = {f
    "srn" = "CreateSonraiInvites.items[0].srn"
  }
```

Then your reader graphql query can look like this: 
```json
query findInvite($srn: String!) {
  findInvite(srn: $srn) {
     . . . 
}
```

And then since `srn` is the only variable you want to pass to your reader query, you can set `read_query_variables = {}` in the resource.

**Comment by sullivtr** [comment]
*NOTE* on the above comment: You MUST have `compute_from_create` set to true in order for your reader query to be able to use a computed variable in its arguments.
