### ISSUE TITLE
Under what circumstances does an "update" get triggered? (server state drift reconciliation)

### ISSUE THREAD

**Issue by ajbouh** [sullivtr/terraform-provider-graphql#47]
I have two uses of this provider and from studying the logs I think both of them are configured wrong. One never seems to run the update mutation (even if it should) and the other runs it every time (even if it shouldn't).

I've gone over the documentation and the source code but I'm still having trouble understanding the logic that determines if an update is necessary.

Before I looked at the code, I had assumed that the update operation runs if the `create_mutation_keys` values that do not match `mutation_variables`. But after reading the implementation I now that's not actually true.

What's the algorithm? Is it possible to identify which paths in the read operation should be compared to mutation variables?

**Comment by QuingKhaos** [comment]
Hi @sullivtr, another feedback from using a bunch of different providers on my side.

> I always figured it would be quite dangerous for the provider to automatically undo changes carried out remotely outside of terraform, which is why I have not thought to implement it that way. With that said, it is also fair to expect that the provider will be able to undo changes made remotely.

With Infrastructure as Code, the Terraform manifest should be the only source of truth. One advantage of using Terraform (compared to e.g. CloudFormation on AWS) is that it is able to detect drift/changes made outside of Terraform and reconcile them back to the desired state in the manifests.

Speaking, your provider should execute the update mutation if data from the read query has been changed to reconcile the resource back to the desired state in manifests :)

I'll be using this GraphQL provider to create several GitLab resources which are not yet covered by the official GitLab terraform provider, so I'll add further feedback to this issue, how different configurations of the mutation resource are behaving regarding this topic. Managing GitLab resources like Issue Boards are prone to be changed outside of Terraform :))

**Comment by sullivtr** [comment]
@QuingKhaos 

First, I 100% agree that the manifest should be the source of truth, and the way this provider behaves right now is to assume the manifest is always the source of truth. I do plan to make it possible to override server state with this provider (as it should be able to do), but I want to make it clear that its rather reckless to allow outside sources to control the state of the resources you manage in your IAC projects (From experience its a maintenance nightmare)

This is the #1 rule I set for any IAC project. The IAC manifest _must_ be the source of truth. We cannot claim the terraform manifest is the source of truth if we expect server state to drift from the manifests's declared state. If you are managing resources that cannot be controlled by terraform, then the terraform manifest is not the source of truth, it's a mere copy of the source (regardless if it created the resource or not). 

I strongly urge against managing resource's with IAC if you do not have control over the state of the resource. 

With all of that said, I do plan to make this provider behave in such a way that it can use the query stage of an apply to demonstrate the diff, and also be capable of applying the diff if you so desire. I will keep you all up to date on the status of this fix as I find time to implement it.

**Comment by sullivtr** [comment]
Hello everyone, I have created a PR (https://github.com/sullivtr/terraform-provider-graphql/pull/61) that provides a fix for the herein issue. It ensures the provider always checks a diff between TF state and server state of a given resource. If drift is detected, the provider will emit a warning during the plan lifecycle letting you know there is drift, as well as a display of the diff it found.

HOWEVER.. for some reason it will not automatically create the state diff if you are on a TF version `< v1.0.0`. I have found many other such bugs in older versions of Terraform. So just know that if you are on an older version of terraform, you will have to reconcile server state manually. 

This provider is different than most providers, and the mutation inputs do not directly overlap the query_response (its arbitrary data, and mutation_variables are very flexible with how you use them as inputs on your mutations), which is the reason this provider was not doing this before. In order to make this work I have to check for a diff, and essentially empty your mutation_variables inputs to trick terraform into realizing there is state drift it needs to reconcile. I have more details about this implementation but I will spare you all the pain of hearing about it. I hope this PR will suffice. Please comment and let me know what you think.

**Comment by sullivtr** [comment]
https://github.com/sullivtr/terraform-provider-graphql/pull/61#issuecomment-1002284960

After testing some edge cases manually, I have determined that this solution does not provide an acceptable user-experience (introduction of nuanced bugs is unavoidable).

There are a few aspects of this provider that make it very challenging and nearly impossible for it to reconcile the state of a resource when drift occurs (again, this is due to how input values specified on the `mutation_variables` parameter do not overlap/explicitly affect the state of the `query_response` computed value which is used for the diff). Even though the provider sees a change in the `query_response` is has no knowledge of how to correlate that diff to the arbitrary K/Vs supplied in the `mutation_variable` inputs (since those get passed along to your GQL mutations, and the values only find their way into the query response indirectly). 

In most non generic providers, resource inputs are 1:1 with the "state" of the resource such that the plan/query step will update the state of those inputs allowing for accurate drift detection between server state and inputs. However that is not, and cannot be the case with this provider due to the input indirection into arbitrary GQL queries. 

At this point I have spent 10+ hours attempting various possible solutions, and none avoid damaging the user-experience for the _normal_ provider use-cases where server drift is avoided. It is very likely I will decide not to support this, especially since the need for it is indicative of improper use of IAC for the general use of this type of tooling.

**Comment by ajbouh** [comment]
First, thanks for investing so much time in figuring this out!

I understand the proper ways to use IAC but I'd like to underscore that the ideal is essentially impossible to achieve in practice.

This especially true when dealing with third party graphql APIs. 

Take, for example, the case of an upstream API that has a bug in it. Once the upstream API is fixed, the "right" thing to do here would be to re-run terraform and let the graphql provider detect the drift and come up with a plan to mutate it back to the desired state.

Every other terraform provider I know of would tolerate this scenario without major problems.

To make this clear, let's imagine AWS reported that a resource was created but failed to actually create it (perhaps due to an outage or other temporary issue). If the AWS terraform provider adopted my understanding of the policy you've described here, your terraform state would be hopelessly wedged and users would never really understand what was going on.

**Comment by sullivtr** [comment]
@ajbouh in a quest to see how this is handled in the restAPI provider, it seems they have the same issue, for much of the same reason I have explained in previous comments (issue here: https://github.com/Mastercard/terraform-provider-restapi/issues/81). 

While the correct behavior is what you see and expect in most providers, this and other providers like it that offer a generic terraform wrapper for CRUDing arbitrary APIs is not _most providers_. I'm not using that statement as an excuse to not solve this problem, but so that users of this provider understand that it is ultimately stretching terraform thin in order to provide some level of management over cloud API resources which do not have a dedicated provider. Terraform was never really meant to manage arbitrary resources like this. (Frankly, its a miracle this provider has worked for so many people so far).

For dedicated providers, we have a strict schema which can be used to manifest and represent the state of the resource, but with this provider, there is a bit of _magic_ under the hood that makes this possible. Unfortunately, that _magic_ is the very thing that makes the server-state drift reconciliation very challenging to accomplish without disrupting other _normal_ TF provider behavior. The tradeoffs would not be welcome (like having weird warning show up indicating state has drifted when it has not, due to the order in which TF must checks that state after an update. That is, diff check must happen in the provider's read function, but the read function must be called after an update causing an interest diff check sequence that results in false negatives. ). 

One other option I tried was having the provider automatically update the server state when it drifts, but that is very unfriendly, as users wont know that it happened. At this point I am stumped, and not sure what else to try. My ears are open if anyone has any clever ideas, though. I'm not ready to give up yet.

**Comment by sullivtr** [comment]
Ive thought of one more potential solution. Its a bit tricky, but Ill report back here if it works out

**Comment by sullivtr** [comment]
@ajbouh you will be excited to know that my latest solution is looking promising so far. I essentially create a map between the keys in the query response object, and the values defined by your mutation_variables. The tricky part was making it capable of fuzzy finding the correct key to map when the value is nested in an object of the query response. For example, with my TODO e2e test, we have `userID` mutation variable being mapped to the `user.id` in the query response object. 

So long as I do not find any fatal flaws here, I should have a PR up sometime this week (when I find the time).

**Comment by sullivtr** [comment]
PR: https://github.com/sullivtr/terraform-provider-graphql/pull/62/files

**Comment by ajbouh** [comment]
I think it's alright to demand that the user provide this mapping explicitly. What are your thoughts?

**Comment by sullivtr** [comment]
> I think it's alright to demand that the user provide this mapping explicitly. What are your thoughts?

In this particular case, my solution in that PR can reliably and accurately build the map. There is one particular edge case that could cause a break, but it's rather nuanced and unlikely (and even if it does occur, will likely not be problematic due to how this works). 

Requiring user input on this would not be a _completely breaking_ change, but is cumbersome enough that I didn't want to go that route (although, it was the first thing I considered). In the rare chance the solution in #62 does not reliably build the map for some strange edge cases, requiring users to supply the mapping will be the route I take. 

If you are in a position to locally test the solution provided in #62, that would also be helpful in informing how I proceed. The cases Ive tested myself have been successful, but I am sure someone out there has something that will send me back down this rabbit hole somehow 😆

**Comment by sullivtr** [comment]
The fix for this is available in v.2.5.0
