### ISSUE TITLE
Apply after create always shows changes since 2.5.0

### ISSUE THREAD

**Issue by jsbnr** [sullivtr/terraform-provider-graphql#70]
Hi. I really like your provider but I'm having trouble with the update always seeing changes after inital apply. With version 2.4.0 this all works as expected but in 2.5.0+ this fails consistently. 

**What  I expect:**
I expect that after the first apply (which creates the resource) a subsequent apply would see no changes. Only when changing the payload input (the variable 'dashboard' in my case) would I expect a change to be required.

**What I get in 2.4.0:**
This works as expected

**What I get in 2.5.1:**
After the first apply, subsequent applies always see a change. The change appears to be the 'dashboard' variable being changed from empty to the value provided in the HCL.

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # graphql_mutation.dashboard will be updated in-place
  ~ resource "graphql_mutation" "dashboard" {
        id                                  = "1"
      ~ mutation_variables                  = {
          ~ "dashboard" = <<-EOT
              + {
              +   "name": "Test GQL",
                    ...snip rest of json object...
              + }
            EOT
        }
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
``` 

I can see this is talked about in issue #64 . In my terraform (v1.1.3 & 1.1.7 tested) *show* i can see this value for query_response_input_key_map is indeed empty:

```
 query_response_input_key_map        = {
        "dashboard" = ""
    }
```

It appears in that other issue #64 you suggest that the read query should return the value used in the input mutation_variables . However this is not striaght forward as the variable itself is a complex json structure which is also nested slightly. I include config below. I wonder if there is a way to 'ignore' upstream changes and only apply chnages when the json itself is changed.

main.tf:
```
resource "graphql_mutation" "dashboard" {
  mutation_variables = {
    dashboard = file("./dashQueries/dash.json")  # This is a json payload
  }
  compute_mutation_keys = {
    "guid" = "dashboardCreate.entityResult.guid"  # The guid from the the create is used for update, read, destroy
  }
  compute_from_create = true
  create_mutation = file("./dashQueries/createMutation.gql")
  update_mutation = file("./dashQueries/updateMutation.gql")
  delete_mutation = file("./dashQueries/deleteMutation.gql")
  read_query      = file("./dashQueries/readQuery.gql")
}
```

create mutation:
```
mutation create($dashboard: DashboardInput!) {
  dashboardCreate(accountId: 1, dashboard: $dashboard) {
    entityResult {
      name
      guid
    }
  }
}
```

read query:
```
query ($guid: [EntityGuid]!) {
    actor {
      entity(guid: $guid) {
        ... on DashboardEntity {
          name
          guid
        }
      }
    }
  }
```

update mutation:
```
mutation update($dashboard: DashboardInput!, $guid: EntityGuid!) {
  dashboardUpdate( dashboard: $dashboard, guid: $guid) {
    entityResult {
      name
      guid
    }
  }
}
```

Thank you for any time you can spend looking at this!

**Comment by sullivtr** [comment]
Hey @jsbnr. Thanks for submitting this issue. I’ll be looking into this. I’m currently on vacation without a laptop but will help you address it when I return. 
Thank you for your patience 😊

**Comment by sullivtr** [comment]
Just thought of one thing in the meantime worth trying:

the provider actually compares the mutation variable as a json encoded blob before diving into individual values, so as long as the dashboard object is fully represented in the read query response with all of the properties you set in the json payload, it _should_ be able to succeed in finding it. For example, right now you only return the name and guid, but if you add all of the same properties that you send in, should be g2g.

can you try this and let me know? (Again apologies since I’m helping from my phone so I might be missing something).

**Comment by jsbnr** [comment]
Thanks for looking at this. I tried changing the read to return all the fields, but I cant seem to get the read to be the same shape as the create mutation. Its also not really scaleable as the source JSON is user specified and may containt different fields from those expected and the order of those fields might be rreturned differently too. Ideally i want to treat the whole JSON as a blob rather than the provider trying to diff multiple attributes within (there could be hundreds). I suppose the requirement might be be that the provider can be configured to only perform an update if the source JSON provided in the `dash.json` file has changed and it disregards any changes in the resource field itself.

**Comment by sullivtr** [comment]
>I suppose the requirement might be be that the provider can be configured to only perform an update if the source JSON provided in the dash.json file has changed and it disregards any changes in the resource field itself.

So this is _technically_ what it's doing now. The problem is that it needs a source to compare against. In the past (< v2.4.0) it was comparing against its own state, which led to a more dangerous problem of the provider not detecting remote state drift. Therefore, in v2.5.0 I updated the provider to compare changes with the remote state of a resource (which is the correct behavior which I avoided for so long primarily due to the issue you are experiencing). 

The provider does treat the entire JSON object as a blob _first_ and if it does not match, it begins to dive down into child objects of the json in a recursive loop. So it goes: 
- Compare json encoded blob -> 
- no match -> 
- compare child properties -->
  -  If child prop is also a json object, compare it as a blob first before diving to its individual properties, 
 - and so on . . . 

I think the only real option I have for you at the moment is to potentially add a config flag for the resource to avoid comparing remote state (essentially the pre-2.5.0 functionality). I'm not a huge fan of this since it technically not the correct pattern to be followed. However, as I mentioned, we made it to 2.4.0 without remote state diffing primarily because I knew issues like this would exist on the types of arbitrary inputs different use-cases present. 

Give me some time to think on this, and Ill report back here my plan. In the meantime, it wont hurt you at all to continue using v2.4.0, as there are no other features outside of the remote state diffing between 2.4 and 2.5.

**Comment by jsbnr** [comment]
Hmm a tough one :) A flag sounds like a good solution. For your reference I have published the working version of the terraform using v2.4.0 here: https://github.com/jsbnr/nr-terraform-graphql-json-dashboards

**Comment by jsbnr** [comment]
@sullivtr Just wondering if you had any more thoughts on providing configuraiton option to allow remote state diff to be ignored?

**Comment by sullivtr** [comment]
@jsbnr I am actually beginning work on this today. Ive been eyeing this, honestly debating if I should support the option of turning off the remote state reconciler, as doing so introduces nuance to the provider Im not sure I want to support longer term. With that said, Im going to take a crack at it and see if its trivial enough not to cause problems.

**Comment by sullivtr** [comment]
Ok @jsbnr I have just release `v2.5.2` of the provider, which now offers a new input, `enable_remote_state_verification`.

Set `enable_remote_state_verification = false` to disable the reconciling logic. This should result in the same behavior we see in >= v2.4.0

**Comment by jsbnr** [comment]
Thanks so much for this @sullivtr.  Im seeing some odd behaviour still with that flag, ill raise as a new issue though.
